# Site settings
title: Your Portfolio Title
description: A brief description of your portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Customize the navigation links
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact

# Specify the colors and styles
colors:
  primary: "#007bff" # Change this to your preferred primary color
  secondary: "#6c757d" # Change this to your preferred secondary color
  background: "#f8f9fa" # Change this to your preferred background color
  text: "#343a40" # Change this to your preferred text color
  link: "#007bff" # Change this to your preferred link color

# Specify the layout settings
layout:
  header:
    background_color: "{{ colors.primary }}"
    text_color: "{{ colors.background }}"
  footer:
    background_color: "{{ colors.primary }}"
    text_color: "{{ colors.background }}"

# Specify any other custom settings or configurations
