title: Paul-Emmanuel Fulgence Atte
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal
description: Contact me on Linkedin: [https://www.linkedin.com/in/paul-emmanuel-fulgence-att%C3%A9-0550a852/]
